# Script mode: turns a list of files into one C++ translation unit that registers
# them with pf::register_embedded_resources at static-init time.
#
#   cmake -DOUTPUT=<file.cpp> "-DINPUTS=a;b" "-DNAMES=a.css;b.htm" -P embed_resources.cmake

set(generated "// Generated by platform_add_app(EMBED ...). Do not edit.\n\n")
string(APPEND generated "#include \"platform.h\"\n\n#include <cstdint>\n#include <iterator>\n\nnamespace\n{\n")

set(index 0)
foreach(input IN LISTS INPUTS)
    list(GET NAMES ${index} name)

    if(NOT EXISTS "${input}")
        message(FATAL_ERROR "embed_resources: '${input}' does not exist.")
    endif()

    file(READ "${input}" hex HEX)
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")

    # CMake regexes have no {n} quantifier, so the 16-byte row is spelled out.
    string(REPEAT "0x..," 16 row)
    string(REGEX REPLACE "(${row})" "\\1\n\t\t" bytes "${bytes}")

    # The trailing NUL is not counted in the size, so embedded_resource_text can
    # hand out a null-terminated view of a file that never contained one.
    string(APPEND generated "\tconst uint8_t blob_${index}[] = {\n\t\t${bytes}0x00\n\t};\n\n")

    math(EXPR index "${index} + 1")
endforeach()

string(APPEND generated "\tconst pf::embedded_resource table[] = {\n")

set(index 0)
foreach(name IN LISTS NAMES)
    string(APPEND generated "\t\t{\"${name}\", blob_${index}, sizeof(blob_${index}) - 1},\n")
    math(EXPR index "${index} + 1")
endforeach()

string(APPEND generated "\t};\n\n")
string(APPEND generated "\tconst bool registered = (pf::register_embedded_resources(table, std::size(table)), true);\n")
string(APPEND generated "}\n")

file(WRITE "${OUTPUT}" "${generated}")
