# platform_add_app() — declares a platform-h application.
#
# Everything that has to live in the executable's resource table (icon,
# manifest, version info) is described here rather than in a hand-maintained
# .rc; the .rc is generated. Data files are embedded as C++ arrays and reached
# through pf::embedded_resource_*, which works on every backend.
#
#   platform_add_app(potato
#       SOURCES     src/main.cpp src/document.cpp
#       ICON        src/res/potato.ico
#       DESCRIPTION "Potato browser"
#       OUTPUT_NAME potato-64
#       EMBED       src/res/master.css src/res/test.htm)

# The function body runs in the caller's directory scope, so this has to be
# reachable from anywhere, not just from platform-h's own scope.
set(PLATFORM_H_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE INTERNAL "platform-h cmake helpers")

function(platform_add_app target)
    cmake_parse_arguments(PA
        "CONSOLE"
        "ICON;MANIFEST;DESCRIPTION;OUTPUT_NAME;VERSION;COMPANY"
        "SOURCES;EMBED"
        ${ARGN})

    if(NOT PA_SOURCES)
        message(FATAL_ERROR "platform_add_app(${target}): SOURCES is required.")
    endif()

    set(generated_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/${target}")
    file(MAKE_DIRECTORY "${generated_dir}")

    set(sources ${PA_SOURCES})

    if(NOT PA_VERSION)
        set(PA_VERSION "${PROJECT_VERSION}")
    endif()
    if(NOT PA_VERSION)
        set(PA_VERSION "0.0.0.0")
    endif()
    if(NOT PA_OUTPUT_NAME)
        set(PA_OUTPUT_NAME "${target}")
    endif()
    if(NOT PA_DESCRIPTION)
        set(PA_DESCRIPTION "${target}")
    endif()

    # --- embedded data files -------------------------------------------------
    if(PA_EMBED)
        set(embed_inputs "")
        set(embed_names "")
        foreach(item IN LISTS PA_EMBED)
            get_filename_component(absolute "${item}" ABSOLUTE)
            get_filename_component(name "${item}" NAME)
            list(APPEND embed_inputs "${absolute}")
            list(APPEND embed_names "${name}")
        endforeach()

        set(embed_cpp "${generated_dir}/embedded_resources.cpp")
        add_custom_command(
            OUTPUT "${embed_cpp}"
            COMMAND "${CMAKE_COMMAND}"
                    "-DOUTPUT=${embed_cpp}"
                    "-DINPUTS=${embed_inputs}"
                    "-DNAMES=${embed_names}"
                    -P "${PLATFORM_H_CMAKE_DIR}/embed_resources.cmake"
            DEPENDS ${embed_inputs} "${PLATFORM_H_CMAKE_DIR}/embed_resources.cmake"
            COMMENT "Embedding ${target} resources"
            VERBATIM)

        list(APPEND sources "${embed_cpp}")
        set_source_files_properties("${embed_cpp}" PROPERTIES SKIP_PRECOMPILE_HEADERS ON)
    endif()

    if(WIN32)
        # --- manifest --------------------------------------------------------
        if(NOT DEFINED PA_MANIFEST)
            set(PLATFORM_APP_NAME "${PA_OUTPUT_NAME}.exe")
            set(PLATFORM_APP_VERSION "${PA_VERSION}")
            if(NOT PLATFORM_APP_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$")
                set(PLATFORM_APP_VERSION "${PLATFORM_APP_VERSION}.0")
            endif()
            set(PLATFORM_APP_DESCRIPTION "${PA_DESCRIPTION}")

            set(manifest "${generated_dir}/${target}.manifest")
            configure_file("${PLATFORM_H_CMAKE_DIR}/app.manifest.in" "${manifest}" @ONLY)
            list(APPEND sources "${manifest}")
        elseif(NOT PA_MANIFEST STREQUAL "NONE")
            list(APPEND sources "${PA_MANIFEST}")
        endif()

        # --- generated resource script ---------------------------------------
        string(REPLACE "." "," rc_version "${PA_VERSION}")
        string(REGEX REPLACE "^([0-9]+,[0-9]+,[0-9]+)$" "\\1,0" rc_version "${rc_version}")

        set(rc "// Generated by platform_add_app(). Do not edit.\n#include <windows.h>\n\n")

        if(PA_ICON)
            get_filename_component(icon_path "${PA_ICON}" ABSOLUTE)
            if(NOT EXISTS "${icon_path}")
                message(FATAL_ERROR "platform_add_app(${target}): ICON '${icon_path}' does not exist.")
            endif()
            file(TO_NATIVE_PATH "${icon_path}" icon_native)
            string(REPLACE "\\" "\\\\" icon_native "${icon_native}")
            # ID 1: the lowest icon ID is the one the shell shows for the exe.
            string(APPEND rc "1 ICON \"${icon_native}\"\n\n")
        endif()

        string(APPEND rc "VS_VERSION_INFO VERSIONINFO\n")
        string(APPEND rc " FILEVERSION ${rc_version}\n PRODUCTVERSION ${rc_version}\n")
        string(APPEND rc " FILEFLAGSMASK 0x3fL\n FILEFLAGS 0x0L\n FILEOS VOS_NT_WINDOWS32\n")
        string(APPEND rc " FILETYPE VFT_APP\n FILESUBTYPE VFT2_UNKNOWN\nBEGIN\n")
        string(APPEND rc "  BLOCK \"StringFileInfo\"\n  BEGIN\n    BLOCK \"040904b0\"\n    BEGIN\n")
        string(APPEND rc "      VALUE \"FileDescription\", \"${PA_DESCRIPTION}\"\n")
        string(APPEND rc "      VALUE \"FileVersion\", \"${PA_VERSION}\"\n")
        string(APPEND rc "      VALUE \"InternalName\", \"${target}\"\n")
        string(APPEND rc "      VALUE \"OriginalFilename\", \"${PA_OUTPUT_NAME}.exe\"\n")
        string(APPEND rc "      VALUE \"ProductName\", \"${target}\"\n")
        string(APPEND rc "      VALUE \"ProductVersion\", \"${PA_VERSION}\"\n")
        if(PA_COMPANY)
            string(APPEND rc "      VALUE \"CompanyName\", \"${PA_COMPANY}\"\n")
        endif()
        string(APPEND rc "    END\n  END\n  BLOCK \"VarFileInfo\"\n  BEGIN\n")
        string(APPEND rc "    VALUE \"Translation\", 0x409, 1200\n  END\nEND\n")

        set(rc_file "${generated_dir}/${target}.rc")
        file(GENERATE OUTPUT "${rc_file}" CONTENT "${rc}")
        list(APPEND sources "${rc_file}")
    endif()

    if(PA_CONSOLE)
        add_executable(${target} ${sources})
    else()
        add_executable(${target} WIN32 ${sources})
    endif()

    target_link_libraries(${target} PRIVATE platform::platform)
    set_target_properties(${target} PROPERTIES OUTPUT_NAME "${PA_OUTPUT_NAME}")
endfunction()
